name: Generate GitHub Calendar source

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          
      - name: yarn install
        working-directory: github-calendar-generator
        run: yarn

      - name: Run
        working-directory: github-calendar-generator
        run: node index.js

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: S3 sync
        working-directory: github-calendar-generator/dist
        run: aws s3 sync calendar.html s3://github-calendar --delete --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers

