name: Generate GitHub Calendar source

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          
      - name: yarn install
        run: | 
          cd github-calendar-generator
          yarn

      - name: Run
        run: |
          cd github-calendar-generator
          node index.js
